spring.application.name=MediRoutine

# ===============================
# Supabase PostgreSQL
# ===============================

spring.datasource.url=jdbc:postgresql://db.vmpzdwaeqjyfspqdrcix.supabase.co/postgres
spring.datasource.username=postgres
spring.datasource.password=ce79-ce80-ce83
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Server
# ===============================

server.port=8080