CREATE TABLE "public"."medicine_logs" (
  "id"             bigint                         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "action_time"    timestamp(6) without time zone,
  "scheduled_date" date                           NOT NULL,
  "scheduled_time" time(0) without time zone      NOT NULL,
  "status"         character varying(255)         NOT NULL,
  "schedule_id"    bigint                         NOT NULL,
  CONSTRAINT "medicine_logs_pkey" PRIMARY KEY (id),
  CONSTRAINT "medicine_logs_status_check" CHECK (((status)::text = ANY ((ARRAY['TAKEN'::character varying, 'MISSED'::character varying, 'SKIPPED'::character varying])::text[])))
);

CREATE TABLE "public"."medicine_schedules" (
  "id"             bigint                    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "days_of_week"   character varying(255),
  "dosage"         character varying(255),
  "end_date"       date,
  "frequency_type" character varying(255)    NOT NULL,
  "interval_days"  integer,
  "period"         character varying(255)    NOT NULL,
  "quantity"       integer,
  "start_date"     date                      NOT NULL,
  "time"           time(0) without time zone NOT NULL,
  "unit"           character varying(255),
  "medicine_id"    bigint                    NOT NULL,
  CONSTRAINT "medicine_schedules_frequency_type_check"
    CHECK
    (((frequency_type)::text = ANY ((ARRAY['DAILY'::character varying, 'SPECIFIC_DAYS'::character varying, 'EVERY_N_DAYS'::character varying, 'AS_NEEDED'::character
    varying])::text[]))),
  CONSTRAINT "medicine_schedules_period_check"
    CHECK (((period)::text = ANY ((ARRAY['MORNING'::character varying, 'AFTERNOON'::character varying, 'NIGHT'::character varying])::text[]))),
  CONSTRAINT "medicine_schedules_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."medicines" (
  "id"          bigint                 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "description" character varying(255),
  "name"        character varying(255) NOT NULL,
  "user_id"     bigint                 NOT NULL,
  CONSTRAINT "medicines_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."users" (
  "id"       bigint                 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email"    character varying(255) NOT NULL,
  "name"     character varying(255),
  "password" character varying(255),
  CONSTRAINT "uk6dotkott2kjsp8vw4d0m25fb7" UNIQUE (email),
  CONSTRAINT "users_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."medicine_logs"
  ADD CONSTRAINT "fkd5xs4tdk51t9xs2f1pf506p81" FOREIGN KEY (schedule_id) REFERENCES public.medicine_schedules(id);

ALTER TABLE "public"."medicine_schedules"
  ADD CONSTRAINT "fkhkhm6svqkhvtq34j3m9jlpsgp" FOREIGN KEY (medicine_id) REFERENCES public.medicines(id);

ALTER TABLE "public"."medicines"
  ADD CONSTRAINT "fk3nje7c71dsgmn88656kyithyw" FOREIGN KEY (user_id) REFERENCES public.users(id);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."medicine_logs" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."medicine_schedules" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."medicines" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "anon", "authenticated", "postgres", "service_role";

